### ISSUE TITLE
Some commands give error in version 1.12.2

### ISSUE THREAD

**Issue by TeQTabanca** [WeaponMechanics/MechanicsMain#123]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

**It gives an error when I type "/wm help 2-3-4...". Finally, when I type "/wm test < firework, recoil, fakeentity, hitbox and mask" commands, it gives an error in the console.**

### Expected Behavior

**Commands should run without errors.**

### Steps To Reproduce

1- I'm typing the commands I specified,
2- and I get error in console.

### Frequency

%100

### Version and Log

![image](https://user-images.githubusercontent.com/89253304/175099827-64ed5372-64bb-47b1-9001-aa4167954418.png)

### /wm help 2

> [19:10:44 INFO]: TeqTabanca issued server command: /wm help 2
> [19:10:44 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing 'wm help 2' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/hover/content/Content
>         at me.deecaad.core.commands.SubCommand.sendHelp(SubCommand.java:157) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.SubCommands.sendHelp(SubCommands.java:163) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.MainCommand.help(MainCommand.java:58) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:91) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 14 more
> Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.hover.content.Content
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
>         at me.deecaad.core.commands.SubCommand.sendHelp(SubCommand.java:157) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.SubCommands.sendHelp(SubCommands.java:163) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.MainCommand.help(MainCommand.java:58) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:91) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 14 more

### /wm test firework

> [19:13:06 INFO]: TeqTabanca issued server command: /wm test firework
> [19:13:06 ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing 'wm test firework' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.NoSuchFieldError: FIREWORK_ROCKET
>         at me.deecaad.weaponmechanics.commands.testcommands.FireworkCommand.execute(FireworkCommand.java:49) ~[WeaponMechanics-1.8.2-BETA.jar:?]
>         at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.weaponmechanics.commands.testcommands.TestCommand.execute(TestCommand.java:29) ~[WeaponMechanics-1.8.2-BETA.jar:?]
>         at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:86) ~[MechanicsCore-1.3.2-BETA.jar:?]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 14 more

### /wm test recoil

> [19:14:38 INFO]: TeqTabanca issued server command: /wm test recoil
[19:14:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'wm test recoil' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at me.deecaad.weaponmechanics.commands.testcommands.RecoilCommand.execute(RecoilCommand.java:26) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.TestCommand.execute(TestCommand.java:29) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:86) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 14 more

### /wm test shoot

> [19:15:43 INFO]: TeqTabanca issued server command: /wm test shoot
[19:15:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'wm test shoot' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at me.deecaad.weaponmechanics.commands.testcommands.ShootCommand.execute(ShootCommand.java:25) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.TestCommand.execute(TestCommand.java:29) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:86) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 14 more

### /wm test fakeentity

> [19:16:21 INFO]: TeqTabanca issued server command: /wm test fakeentity
[19:16:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'wm test fakeentity' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_12_R1.Entity.setCustomName(Entity.java:2518) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at me.deecaad.core.compatibility.entity.FakeEntity_1_12_R1.setDisplay(FakeEntity_1_12_R1.java:118) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.FakeEntityCommand.execute(FakeEntityCommand.java:46) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.TestCommand.execute(TestCommand.java:29) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:86) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 14 more

### /wm test hitbox (After looking at the entity and typing, it sends spam to the console. It does not give an error as a message.)

> [19:24:18 WARN]: [WeaponMechanics] Plugin WeaponMechanics v1.8.2-BETA generated an exception while executing task 5384
java.lang.NoSuchMethodError: 'org.bukkit.util.BoundingBox org.bukkit.entity.Entity.getBoundingBox()'
        at me.deecaad.weaponmechanics.commands.testcommands.HitboxCommand$1.run(HitboxCommand.java:74) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

### /wm test mask

> [19:16:54 INFO]: TeqTabanca issued server command: /wm test mask
[19:16:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'wm test mask' in me.deecaad.weaponmechanics.commands.WeaponMechanicsMainCommand(weaponmechanics)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class net.minecraft.server.v1_12_R1.Packet (java.util.ArrayList is in module java.base of loader 'bootstrap'; net.minecraft.server.v1_12_R1.Packet is in unnamed module of loader 'app')
        at me.deecaad.core.compatibility.v1_12_R1.sendPackets(v1_12_R1.java:58) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.MaskCommand.execute(MaskCommand.java:79) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.weaponmechanics.commands.testcommands.TestCommand.execute(TestCommand.java:29) ~[WeaponMechanics-1.8.2-BETA.jar:?]
        at me.deecaad.core.commands.SubCommands.execute(SubCommands.java:179) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at me.deecaad.core.commands.MainCommand.execute(MainCommand.java:86) ~[MechanicsCore-1.3.2-BETA.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        ... 14 more

**Comment by CJCrafter** [comment]
WeaponMechanics has an advanced command system that only works in 1.13+ that fixes these errors. While WeaponMechanics does support 1.9 through 1.12.2, it uses many *"legacy"* systems that I simply do not have the time to update. Our focus is on newer Minecraft versions, while continuing to ensure the plugin works across all possible Minecraft versions. 

The errors you recieved occurred because you used the command wrong, they are expecting arguments. Try pressing `tab`, or using the help command.
