### ISSUE TITLE
Explosion Block_Damage

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#16]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [x] I have asked for help

### Current Behavior

When only `$GLASS` is defined in `Block_List` and `Spawn_Falling_Block_Chance: 0.75`  

1) With `Blacklist: true`  
All blocks expect GLASS gets destroyed, but `Spawn_Falling_Block_Chance` is also used for GLASS blocks that aren't destroyed. This is only a visual bug.

2) With `Blacklist: false`
Correct blocks (`GLASS`) gets destroyed properly. `Null` is thrown at [this line](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/weapon/explode/Explosion.java#L368). Id expect spawn falling block bug is here also for all blocks.

### Expected Behavior

When a block isn't actually destroyed its falling blocks won't be sent either

### Steps To Reproduce

```yaml
RPG-7:
  Info:
    Weapon_Item:
      Type: "FEATHER"
      Name: "&6RPG-7"
      Unbreakable: true
      Hide_Flags: true
      Attributes:
        - "GENERIC_MOVEMENT_SPEED--0.02855"
      Deny_Use_In_Crafting: true
    Weapon_Info_Display:
      Action_Bar:
        Message: "&6RPG-7 &7«&6%ammo-left%&7»&6%reload%"
        Time: 40
    Weapon_Get_Mechanics:
      Sounds:
        - "ITEM_ARMOR_EQUIP_CHAIN-1-0.75"
    Cancel:
      Drop_Item: true
      Swap_Hands: true
      Arm_Swing_Animation: true
  Skin:
    Default:
      Custom_Model_Data: 101
    Scope:
      Custom_Model_Data: 111
  Projectile: "rocket_launcher.Projectile"
  Shoot:
    Trigger:
      Main_Hand: "RIGHT_CLICK"
      Off_Hand: "RIGHT_CLICK"
      Deny_When:
        Swimming: true
    Projectile_Speed: 40
    Spread:
      Base_Spread: 0.55
      Modify_Spread_When:
        Zooming: 50%
        Sneaking: 50%
        Walking: 0.1
        In_Midair: 150%
        Gliding: 200%
    Recoil:
      Push_Time: 200
      Recover_Time: 200
      Horizontal:
        - 11
        - -11
      Vertical:
        - 11
    Mechanics:
      Sounds:
        - "custom:shoot.rpg7-6-1-0-0.1"
  Reload:
    Trigger:
      Main_Hand: "DROP_ITEM"
      Off_Hand: "DROP_ITEM"
    Magazine_Size: 1
    Reload_Duration: 71
    Start_Mechanics:
      Sounds:
        - "BLOCK_NOTE_BLOCK_HAT-0.5-1-0-0.1"
        - "BLOCK_PISTON_CONTRACT-0.5-1-2-0.1"
        - "ITEM_FLINTANDSTEEL_USE-0.5-1.5-33"
        - "ITEM_FLINTANDSTEEL_USE-0.5-1.7-35"
        - "ITEM_FLINTANDSTEEL_USE-0.5-1.9-37"
        - "BLOCK_PISTON_EXTEND-0.5-1-69-0.1"
  Damage:
    Base_Damage: 12.2
    Base_Explosion_Damage: 12.2
    Fire_Ticks: 40
    Armor_Damage: 4
  Explosion:
    Explosion_Exposure: "DEFAULT"
    Explosion_Shape: "SPHERE"
    Explosion_Type_Data:
      Radius: 5.6
    Detonation:
      Impact_When:
        Entity: true
        Block: true
    Block_Damage:
      Break_Blocks: true
      Spawn_Falling_Block_Chance: 0.75
      Blacklist: false
      Block_List:
        - "$GLASS"
    Regeneration:
      Ticks_Before_Start: 300
      Max_Blocks_Per_Update: 3
      Ticks_Between_Updates: 5
    Flashbang:
      Effect_Distance: 11.2
      Mechanics:
        Potion_Effects:
          - "CONFUSION-200-3-false"
  Scope:
    Trigger:
      Main_Hand: "LEFT_CLICK"
      Off_Hand: "LEFT_CLICK"
    Zoom_Amount: 6
    Mechanics:
      Sounds:
        - "custom:scope.in-0.5-1-0-0.1"
    Zoom_Off:
      Mechanics:
        Sounds:
          - "custom:scope.out-0.5-1-0-0.1"

rocket_launcher:
  Projectile:
    Projectile_Settings:
      Type: "WITHER_SKULL"
      Minimum:
        Speed: 25
      Gravity: 0.02
      Decrease_Motion:
        Base: 0.99
        In_Water: 0.96
        When_Raining_Or_Snowing: 0.98
```

### Frequency

100%

### Version and Log

https://imgur.com/qqsEO7Z

```
[21:17:10] [Server thread/WARN]: [WeaponMechanics] Task #524 for WeaponMechanics v0.3.0 generated an exception
java.lang.NullPointerException: Cannot invoke "me.deecaad.weaponmechanics.weapon.damage.BlockDamageData$DamageData.isBroken()" because "data" is null
        at me.deecaad.weaponmechanics.weapon.explode.Explosion.damageBlocks(Explosion.java:368) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.explode.Explosion.explode(Explosion.java:273) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.RayTraceResult$1.run(RayTraceResult.java:129) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by CJCrafter** [comment]
Forgot to check if a block was blacklisted from block damage, fixed in commit https://github.com/WeaponMechanics/MechanicsMain/commit/6129b42a155ec03656faf56d28dad96f8347569d
