### ISSUE TITLE
"MySQL Player Data Bridge" compatibility error

### ISSUE THREAD

**Issue by MelonHell** [WeaponMechanics/MechanicsMain#165]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

When using the "MySQL Player Data Bridge" plugin, an exception is thrown that mentions MechanicsCore

### Expected Behavior

no exceptions

### Steps To Reproduce

1. install "MySQL Player Data Bridge"
2. just change server

### Frequency

almost constantly

### Version and Log

Paper 1.19.2 (b138)
MechanicsCore 1.5.6
MySQL Player Data Bridge 4.6.0
```
java.lang.IllegalStateException: EntityEquipmentEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:658) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at me.deecaad.core.events.triggers.EquipListener.lambda$inject$1(EquipListener.java:218) ~[MechanicsCore-1.5.6.jar:?]
	at me.deecaad.core.compatibility.equipevent.NonNullList_1_19_R1.set(NonNullList_1_19_R1.java:55) ~[MechanicsCore-1.5.6.jar:?]
	at me.deecaad.core.compatibility.equipevent.NonNullList_1_19_R1.set(NonNullList_1_19_R1.java:16) ~[MechanicsCore-1.5.6.jar:?]
	at net.minecraft.world.entity.player.Inventory.setItem(Inventory.java:493) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:74) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.clear(CraftInventory.java:442) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.clear(CraftInventory.java:448) ~[paper-1.19.2.jar:git-Paper-138]
	at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.backupAndReset(InventoryDataHandler.java:275) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
	at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.onJoinFunction(InventoryDataHandler.java:246) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
	at net.craftersland.data.bridge.utils.Utils.syncCompleteTask(Utils.java:23) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
	at net.craftersland.data.bridge.events.PlayerJoin$1.run(PlayerJoin.java:32) ~[MysqlPlayerDataBridge-v4.6.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-138]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Anything else?

I don't know in which of the two plugins the error is in the code, if the problem is in the "MySQL Player Data Bridge" please close this issue

**Comment by DeeCaaD** [comment]
Apparently that plugin's dev is doing something thats illegal ( modifying entity inventory in async ). So this is something they'll have to fix

**Comment by MelonHell** [comment]
> Apparently that plugin's dev is doing something thats illegal ( modifying entity inventory in async ). So this is something they'll have to fix

thanks, it turned out that the plugin actually changes the inventory asynchronously
