### ISSUE TITLE
Minus leap, isnt working

### ISSUE THREAD

**Issue by ErikViceCode** [WeaponMechanics/MechanicsMain#274]
### Current Behavior

Isnt working Leap

### Expected Behavior

The character must have a recoil

### Steps To Reproduce

https://pastebin.com/r5De6ejA This is config.
you advised me to put such a value on Leap, but it doesn’t work like that, it’s impossible to push back, and Leap also doesn’t work with a minus value
![image](https://user-images.githubusercontent.com/79044354/225298989-6d69b132-9723-44a1-8e8b-bef0d7943289.png)

### Version and Log

Log
`[11:40:35 WARN]: [WeaponMechanics] Task #45282 for WeaponMechanics v2.1.4 generated an exception
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.setVelocity(CraftEntity.java:430) ~[patched_1.16.5.jar:git-Paper-790]
        at me.deecaad.core.mechanics.defaultmechanics.LeapMechanic.use0(LeapMechanic.java:39) ~[?:?]
        at me.deecaad.core.mechanics.defaultmechanics.Mechanic.use(Mechanic.java:93) ~[?:?]
        at me.deecaad.core.mechanics.Mechanics.use(Mechanics.java:56) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.shoot(ShootHandler.java:622) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler$2.run(ShootHandler.java:453) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-790]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-790]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

### Anything else?

No video, AK just no shooting

**Comment by CJCrafter** [comment]
You need to leap toward a target. Consider using `@Source{offset=~0 0 1}` to leap forward

I'll update the wiki to make that more clear
I'll update the code so that error does not occur
