### ISSUE TITLE
Scope issue

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#30]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

Kick & error

### Expected Behavior

Everything goes smoothly

### Steps To Reproduce

1. I assume this is a scope issue

### Frequency

Don't know

### Version and Log

1.18

### Anything else?

https://pastebin.com/8RacwVgf

**Comment by CJCrafter** [comment]
Seems to be related to having multiple people on the server. Can be replicated on a Paper 1.18 server with 2 people on it, with `WeaponMechanics` and `MechanicsCore` being the only plugins. It seems to rather rare though. Proximity might have an effect.

**Comment by CJCrafter** [comment]
Another stack trace 
```
[11:51:18] [Netty Server IO #0/ERROR]: Packet encoding of packet ID 100 threw (skippable? false)
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:142) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.write(ClientboundUpdateAttributesPacket.java:46) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[purpur-1.18.1.jar:git-Purpur-1556]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:16) ~[purpur-1.18.1.jar:git-Purpur-1556]
	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.1.1.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.1.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at me.deecaad.core.packetlistener.PacketListener$PacketInterceptor.write(PacketListener.java:453) ~[MechanicsCore-1.0.2-BETA.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at su.nexmedia.engine.manager.packet.PacketManager$1.write(PacketManager.java:103) ~[NexEngine.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.ChannelProxy.write(ChannelProxy.java:312) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:450) ~[?:?]
	at net.minecraft.network.Connection.lambda$writePacket$7(Connection.java:419) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354) ~[ProtocolLib-4.8.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:51:18] [Server thread/INFO]: HanZia03 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.ConcurrentModificationException
[11:51:18] [Server thread/INFO]: HanZia03 left the game
```

**Comment by DeeCaaD** [comment]
Should be fixed in the next update.

https://github.com/WeaponMechanics/MechanicsMain/commit/c6a518457467c77b87bf75c8727c4f825c390107
