### ISSUE TITLE
[10:21:18 WARN]: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by hed516** [WeaponMechanics/MechanicsMain#320]
### Current Behavior

[10:21:18 WARN]: java.net.ConnectException: Connection refused
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:21:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[10:21:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[10:21:18 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[10:21:18 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.utils.FileUtil.downloadFile(FileUtil.java:183)
[10:21:18 WARN]:        at [枪]WeaponMechanics-2.4.2.jar//me.deecaad.weaponmechanics.WeaponMechanics.lambda$writeFiles$1(WeaponMechanics.java:275)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.file.TaskChain$Task$1.run(TaskChain.java:29)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:21:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:21:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Expected Behavior

[10:21:18 WARN]: java.net.ConnectException: Connection refused
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:21:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[10:21:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[10:21:18 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[10:21:18 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.utils.FileUtil.downloadFile(FileUtil.java:183)
[10:21:18 WARN]:        at [枪]WeaponMechanics-2.4.2.jar//me.deecaad.weaponmechanics.WeaponMechanics.lambda$writeFiles$1(WeaponMechanics.java:275)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.file.TaskChain$Task$1.run(TaskChain.java:29)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:21:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:21:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Steps To Reproduce

[10:21:18 WARN]: java.net.ConnectException: Connection refused
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:21:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[10:21:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[10:21:18 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[10:21:18 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.utils.FileUtil.downloadFile(FileUtil.java:183)
[10:21:18 WARN]:        at [枪]WeaponMechanics-2.4.2.jar//me.deecaad.weaponmechanics.WeaponMechanics.lambda$writeFiles$1(WeaponMechanics.java:275)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.file.TaskChain$Task$1.run(TaskChain.java:29)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:21:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:21:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Version and Log

[10:21:18 WARN]: java.net.ConnectException: Connection refused
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[10:21:18 WARN]:        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[10:21:18 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[10:21:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[10:21:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[10:21:18 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[10:21:18 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[10:21:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[10:21:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.utils.FileUtil.downloadFile(FileUtil.java:183)
[10:21:18 WARN]:        at [枪]WeaponMechanics-2.4.2.jar//me.deecaad.weaponmechanics.WeaponMechanics.lambda$writeFiles$1(WeaponMechanics.java:275)
[10:21:18 WARN]:        at [枪]MechanicsCore-2.4.1.jar//me.deecaad.core.file.TaskChain$Task$1.run(TaskChain.java:29)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:21:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:21:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:21:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:21:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CJCrafter** [comment]
unrelated to wm
