### ISSUE TITLE
WM items compatibility issue with Citizens

### ISSUE THREAD

**Issue by DeeCaaD** [WeaponMechanics/MechanicsMain#36]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

When giving Citizen NPC weapon item this error occurs removing the NPC
```
[17:29:17] [Server thread/ERROR]: Entity threw exception at world:398.5297,32.5,-372.9959
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.c()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:459) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:662) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:653) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.world.entity.LivingEntity.lambda$handleEquipmentChanges$6(LivingEntity.java:3066) ~[?:?]
	at java.util.Map.forEach(Map.java:713) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.handleEquipmentChanges(LivingEntity.java:3065) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:2993) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2895) ~[?:?]
	at net.minecraft.world.entity.decoration.ArmorStand.tick(ArmorStand.java:687) ~[?:?]
	at net.citizensnpcs.nms.v1_18_R1.entity.nonliving.ArmorStandController$EntityArmorStandNPC.k(ArmorStandController.java:113) ~[Citizens-2.0.29-b2464.jar:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-177]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behavior

That error won't happen

### Steps To Reproduce

Give weapon for citizen NPC

### Frequency

100%?

### Version and Log

Paper 1.18.1

**Comment by CJCrafter** [comment]
Citizens is spaghetti code at best... I don't think citizens npcs should be used for weaponmechanics.

**Comment by DeeCaaD** [comment]
I was thinking of simple Sentinel support later.
https://github.com/mcmonkeyprojects/Sentinel/blob/master/src/main/java/org/mcmonkey/sentinel/integration/SentinelCrackShot.java
