### ISSUE TITLE
Errors caused by projectiles

### ISSUE THREAD

**Issue by Ghost067** [WeaponMechanics/MechanicsMain#464]
### Current/Expected Behavior

When I am using version 3.4.14 of WM, the console shows the following error, which is manifested as the failure of the mechanics attached to the weapon. I hope you can fix this problem as soon as possible.

### Steps To Reproduce

When any weapon is fired.

### Log File

[17:18:31 WARN]: [WeaponMechanics] Unhandled exception while ticking projectile! Removing projectile
[17:18:31 WARN]: [WeaponMechanics] Removed Projectile: me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.WeaponProjectile@37e0eba2
java.lang.IllegalArgumentException: Value must be greater than or equal to 0
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftStatistic.setStatistic(CraftStatistic.java:225) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftStatistic.incrementStatistic(CraftStatistic.java:214) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.incrementStatistic(CraftPlayer.java:1060) ~[patched_1.16.5.jar:git-Paper-794]
        at me.deecaad.weaponmechanics.weapon.damage.DamageUtil.apply(DamageUtil.java:208) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:117) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:51) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.damage.DamageHandler.tryUse(DamageHandler.java:45) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleEntityHit(HitHandler.java:146) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.HitHandler.handleHit(HitHandler.java:56) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.WeaponProjectile.updatePosition(WeaponProjectile.java:396) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.AProjectile.tick(AProjectile.java:362) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.tickOnAdd(ProjectilesRunnable.java:101) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.ProjectilesRunnable.addProjectile(ProjectilesRunnable.java:68) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.projectile.weaponprojectile.Projectile.shoot(Projectile.java:105) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.shoot(ShootHandler.java:598) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.singleShot(ShootHandler.java:244) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.shootWithoutTrigger(ShootHandler.java:228) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.shoot.ShootHandler.tryUse(ShootHandler.java:78) ~[?:?]
        at me.deecaad.weaponmechanics.weapon.WeaponHandler.tryUses(WeaponHandler.java:141) ~[?:?]
        at me.deecaad.weaponmechanics.listeners.trigger.TriggerPlayerListeners.interact(TriggerPlayerListeners.java:219) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1070.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:512) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1766) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by CJCrafter** [comment]
Hey Ghost, I can't replicate this bug at all. Looking at the code the stack trace points to, that error shouldn't be remotely possible. Could you have some sort of modified plugin, or server? Or perhaps you have a conflicting plugin? You are the only person to ever reporting something like this.
