### ISSUE TITLE
Ability to disable all kinds of information about weapons.

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/MechanicsMain#80]
### Description

Ability to disable all kinds of information about weapons (action bar, boss bar and etc.) (Needed in order to use action bar and could integrate information about weapons manually, for example through placeholderapi)

### Configuration

    Weapon_Info_Display:
       Enabled: <true/false>

**Comment by DeeCaaD** [comment]
Weapon_Info_Display section can be then simply removed from weapon so it won't be used

**Comment by RollexGrief** [comment]
> Weapon_Info_Display section can be then simply removed from weapon config so it won't be used
if i remove the Weapon_Info_Display i get this warn:
`[22:07:45 WARN]: [WeaponMechanics] Task #136 for WeaponMechanics v1.6.5-BETA generated an exception
java.lang.NullPointerException: Cannot invoke "me.deecaad.weaponmechanics.weapon.info.WeaponInfoDisplay.send(me.deecaad.weaponmechanics.wrappers.PlayerWrapper, org.bukkit.inventory.EquipmentSlot)" because "this.val$weaponInfoDisplay" is null
        at me.deecaad.weaponmechanics.weapon.reload.ReloadHandler$1.setup(ReloadHandler.java:318) ~[WeaponMechanics-1.6.5-BETA.jar:?]
        at me.deecaad.weaponmechanics.weapon.reload.ChainTask.run(ChainTask.java:45) ~[WeaponMechanics-1.6.5-BETA.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-310]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-310]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-310]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
